### ISSUE TITLE
Print type name when logging custom types

### ISSUE THREAD

**Issue by nhgrif** [DrewKiino/Atlantis#1]
In the readme, the following example is provided:

```
public class CustomObject {
    var id: Int = 123
    var name: String = "Ben"
}

let customObject = CustomObject()

log.debug(customObject)

// prints
{
    "id": 123,
    "name": "Doug"
} 
```

It would be nice if it instead printed something more like:

```
<CustomObject: {
    "id": 123,
    "name": "Doug"
}>
```

The actual exact format doesn't exactly matter.  But this is closer what I'd expect to see from `NSLog` in Objective-C for example.  Sometimes it's not just the properties that I'm interested in, but also the type itself.

**Comment by nhgrif** [comment]
Your README also doesn't have any examples using structs, enums, or functions.  Can these be logged?  (It's a slightly different issue, but also slightly the same.)  I would recommend updating the README to make it clear how structs, enums, and functions would be logged.

**Comment by DrewKiino** [comment]
Thanks for the issue, gave me some ideas. I added support for pretty printing enums and structs. Also, added type logging along with log dates. Updated the README as well. 

=> version 1.0.6
